### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by afonsopacifer** [busca-dev/briefing#1]
- [ ] Definir campos
- [ ] Criar Layout
- [ ] Programar interface (seguindo todas as boas práticas)
- [ ] Criar a função de envio de e-mail (Comunicando-se com o Front através de Ajax ;D)
- [ ] Envio de audio
- [ ] Criar generator de yeoman
- [ ] Documentar tudo
